version: "3.9"

services:
  backend:
    container_name: api-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
