# Imagen base
FROM node:22.11.0

# Directorio de trabajo dentro del contened
WORKDIR /app

# Copiamos dependencias e instalamos
COPY package*.json ./
RUN npm install

# Copiamos el resto de la app
COPY . .

# Puerto que expone tu servidor (el de Express)
EXPOSE 3000

# Ejecutamos directamente con Node (sin PM2)
CMD ["node", "src/server.js"]