FROM node:22.11.0

WORKDIR /app

COPY package*.json ./

RUN npm install

# Instalamos pm2 de forma global para correr en clúster
RUN npm install pm2 -g

COPY . .

EXPOSE 3000

# Usamos pm2-runtime que se queda en foreground (buenas prácticas Docker)
CMD ["pm2-runtime", "src/server.js", "-i", "max"]
